Add JER Integration
jbredwards/Subaquatic pull request #70
Opened 2023-11-28 11:25 UTC by Invadermonky

- Added JER integrations
- Adjusted entity loot tables to allow public access
- Fixed Salmon dropping cooked cod when killed while burning

2023-11-28 16:45 UTC, jbredwards requested changes

2023-11-28 16:45 UTC, jbredwards commented on src/main/java/git/jbredwards/subaquatic/mod/Subaquatic.java
> +        if(Loader.isModLoaded(Reference.ID)) {
This line causes a crash while JER isn't present. Can you change this to a constant value without using JER's `Reference` class (like what I did with inspirations [here](https://github.com/jbredwards/Subaquatic/blob/e48e83b39d491a336e789d9b024dda5d4befb34d/src/main/java/git/jbredwards/subaquatic/mod/Subaquatic.java#L97))?

2023-11-28 16:45 UTC, jbredwards commented on src/main/java/git/jbredwards/subaquatic/mod/common/compat/jer/SubaquaticJERPlugin.java
> +        String[] codSpawnBiomes = getBiomeNames(Biomes.OCEAN, Biomes.DEEP_OCEAN, SubaquaticBiomes.COLD_OCEAN, SubaquaticBiomes.DEEP_COLD_OCEAN, SubaquaticBiomes.LUKEWARM_OCEAN, SubaquaticBiomes.DEEP_
Can you change the entity spawn biome arrays to be non-hardcoded values (so things still automatically work as intended if a modpack dev changes the entity spawn biomes)? This can be done by iterating through all registered biomes and saving only the ones that contain the correct entity spawns in `Biome::getSpawnableList`.

2023-11-28 18:09 UTC, Invadermonky commented on src/main/java/git/jbredwards/subaquatic/mod/common/compat/jer/SubaquaticJERPlugin.java
> +        String[] codSpawnBiomes = getBiomeNames(Biomes.OCEAN, Biomes.DEEP_OCEAN, SubaquaticBiomes.COLD_OCEAN, SubaquaticBiomes.DEEP_COLD_OCEAN, SubaquaticBiomes.LUKEWARM_OCEAN, SubaquaticBiomes.DEEP_
This issue is an all or nothing situation. Mods that modify spawning often use their own spawn table group. Iterating through `Biome::getSpawnableList` will only return the spawns that are added to the vanilla `EnumCreatureType`.

I ran into this problem before with JEM and had to scrap the Biome search functions in favor of just using hardcoded values. The best way to handle this is to create a configuration option that allows players to set the entity spawn biomes using the biome registry ID's.

It really comes down to if you want the spawn biomes to display the actual biome name or just go with the generic "Any" text.

2023-11-29 00:49 UTC, Invadermonky commented on src/main/java/git/jbredwards/subaquatic/mod/common/compat/jer/SubaquaticJERPlugin.java
> +        String[] codSpawnBiomes = getBiomeNames(Biomes.OCEAN, Biomes.DEEP_OCEAN, SubaquaticBiomes.COLD_OCEAN, SubaquaticBiomes.DEEP_COLD_OCEAN, SubaquaticBiomes.LUKEWARM_OCEAN, SubaquaticBiomes.DEEP_
If you would like I can write all the associated code for the config biome handlers, I just wanted to keep my impact on your code to a minimum with the JER integration.

2023-11-29 14:55 UTC, jbredwards commented on src/main/java/git/jbredwards/subaquatic/mod/common/compat/jer/SubaquaticJERPlugin.java
> +        String[] codSpawnBiomes = getBiomeNames(Biomes.OCEAN, Biomes.DEEP_OCEAN, SubaquaticBiomes.COLD_OCEAN, SubaquaticBiomes.DEEP_COLD_OCEAN, SubaquaticBiomes.LUKEWARM_OCEAN, SubaquaticBiomes.DEEP_
> Mods that modify spawning often use their own spawn table group

Oh, in that case using hardcoded biomes should be fine 👍

2023-11-29 23:59 UTC, merged